// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScanPoint.Models.Data;

#nullable disable

namespace ScanPoint.Models.Migrations
{
    [DbContext(typeof(ScanPointDbContext))]
    [Migration("20260326123040_RemoveShiftColumnsFromCashier")]
    partial class RemoveShiftColumnsFromCashier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiscountRuleProduct", b =>
                {
                    b.Property<Guid>("DiscountRulesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DiscountRulesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("ProductDiscountRules", (string)null);
                });

            modelBuilder.Entity("ScanPoint.Models.Models.DiscountRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DiscountRules", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ScanPoint.Models.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CashierId");

                    b.HasIndex("ShopId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("ScanPoint.Models.Models.InvoiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("ScanPoint.Models.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ScanPoint.Models.Models.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FiscalNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("ScanPoint.Models.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ScanPoint.Models.Models.BuyXGetYRule", b =>
                {
                    b.HasBaseType("ScanPoint.Models.Models.DiscountRule");

                    b.Property<Guid>("ProductXId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductYId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("XQuantity")
                        .HasColumnType("int");

                    b.Property<int>("YQuantity")
                        .HasColumnType("int");

                    b.ToTable("BuyXGetYRules", (string)null);
                });

            modelBuilder.Entity("ScanPoint.Models.Models.CartTotalDiscountRule", b =>
                {
                    b.HasBaseType("ScanPoint.Models.Models.DiscountRule");

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinCartTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("CartTotalDiscountRules", (string)null);
                });

            modelBuilder.Entity("ScanPoint.Models.Models.ExpirationDiscountRule", b =>
                {
                    b.HasBaseType("ScanPoint.Models.Models.DiscountRule");

                    b.Property<int>("DaysBeforeExpiry")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable("ExpirationDiscountRules", (string)null);
                });

            modelBuilder.Entity("ScanPoint.Models.Models.MaxDiscountLimitRule", b =>
                {
                    b.HasBaseType("ScanPoint.Models.Models.DiscountRule");

                    b.Property<decimal>("MaxDiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("MaxDiscountLimitRules", (string)null);
                });

            modelBuilder.Entity("ScanPoint.Models.Models.ProductTimeBasedDiscountRule", b =>
                {
                    b.HasBaseType("ScanPoint.Models.Models.DiscountRule");

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.ToTable("ProductTimeBasedDiscountRules", (string)null);
                });

            modelBuilder.Entity("ScanPoint.Models.Models.QuantityDiscountRule", b =>
                {
                    b.HasBaseType("ScanPoint.Models.Models.DiscountRule");

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable("QuantityDiscountRules", (string)null);
                });

            modelBuilder.Entity("ScanPoint.Models.Models.Cashier", b =>
                {
                    b.HasBaseType("ScanPoint.Models.Models.User");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ShopId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ShopId1");

                    b.ToTable("Cashiers", (string)null);
                });

            modelBuilder.Entity("ScanPoint.Models.Models.Manager", b =>
                {
                    b.HasBaseType("ScanPoint.Models.Models.User");

                    b.Property<Guid?>("ShopId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("ShopId1");

                    b.ToTable("Managers", (string)null);
                });

            modelBuilder.Entity("DiscountRuleProduct", b =>
                {
                    b.HasOne("ScanPoint.Models.Models.DiscountRule", null)
                        .WithMany()
                        .HasForeignKey("DiscountRulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScanPoint.Models.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScanPoint.Models.Models.Invoice", b =>
                {
                    b.HasOne("ScanPoint.Models.Models.Cashier", "Cashier")
                        .WithMany("Invoices")
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScanPoint.Models.Models.Shop", "Shop")
                        .WithMany("Invoices")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cashier");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("ScanPoint.Models.Models.InvoiceItem", b =>
                {
                    b.HasOne("ScanPoint.Models.Models.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScanPoint.Models.Models.Product", "Product")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ScanPoint.Models.Models.Product", b =>
                {
                    b.HasOne("ScanPoint.Models.Models.Shop", "Shop")
                        .WithMany("Products")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("ScanPoint.Models.Models.Shop", b =>
                {
                    b.HasOne("ScanPoint.Models.Models.User", "Admin")
                        .WithMany("Shops")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("ScanPoint.Models.Models.User", b =>
                {
                    b.HasOne("ScanPoint.Models.Models.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("ScanPoint.Models.Models.BuyXGetYRule", b =>
                {
                    b.HasOne("ScanPoint.Models.Models.DiscountRule", null)
                        .WithOne()
                        .HasForeignKey("ScanPoint.Models.Models.BuyXGetYRule", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScanPoint.Models.Models.CartTotalDiscountRule", b =>
                {
                    b.HasOne("ScanPoint.Models.Models.DiscountRule", null)
                        .WithOne()
                        .HasForeignKey("ScanPoint.Models.Models.CartTotalDiscountRule", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScanPoint.Models.Models.ExpirationDiscountRule", b =>
                {
                    b.HasOne("ScanPoint.Models.Models.DiscountRule", null)
                        .WithOne()
                        .HasForeignKey("ScanPoint.Models.Models.ExpirationDiscountRule", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScanPoint.Models.Models.MaxDiscountLimitRule", b =>
                {
                    b.HasOne("ScanPoint.Models.Models.DiscountRule", null)
                        .WithOne()
                        .HasForeignKey("ScanPoint.Models.Models.MaxDiscountLimitRule", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScanPoint.Models.Models.ProductTimeBasedDiscountRule", b =>
                {
                    b.HasOne("ScanPoint.Models.Models.DiscountRule", null)
                        .WithOne()
                        .HasForeignKey("ScanPoint.Models.Models.ProductTimeBasedDiscountRule", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScanPoint.Models.Models.QuantityDiscountRule", b =>
                {
                    b.HasOne("ScanPoint.Models.Models.DiscountRule", null)
                        .WithOne()
                        .HasForeignKey("ScanPoint.Models.Models.QuantityDiscountRule", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScanPoint.Models.Models.Cashier", b =>
                {
                    b.HasOne("ScanPoint.Models.Models.User", null)
                        .WithOne()
                        .HasForeignKey("ScanPoint.Models.Models.Cashier", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScanPoint.Models.Models.Manager", "Manager")
                        .WithMany("ManagedCashiers")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScanPoint.Models.Models.Shop", null)
                        .WithMany("Cashiers")
                        .HasForeignKey("ShopId1");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("ScanPoint.Models.Models.Manager", b =>
                {
                    b.HasOne("ScanPoint.Models.Models.User", null)
                        .WithOne()
                        .HasForeignKey("ScanPoint.Models.Models.Manager", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScanPoint.Models.Models.Shop", null)
                        .WithMany("Managers")
                        .HasForeignKey("ShopId1");
                });

            modelBuilder.Entity("ScanPoint.Models.Models.Invoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ScanPoint.Models.Models.Product", b =>
                {
                    b.Navigation("InvoiceItems");
                });

            modelBuilder.Entity("ScanPoint.Models.Models.Shop", b =>
                {
                    b.Navigation("Cashiers");

                    b.Navigation("Invoices");

                    b.Navigation("Managers");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("ScanPoint.Models.Models.User", b =>
                {
                    b.Navigation("Shops");
                });

            modelBuilder.Entity("ScanPoint.Models.Models.Cashier", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("ScanPoint.Models.Models.Manager", b =>
                {
                    b.Navigation("ManagedCashiers");
                });
#pragma warning restore 612, 618
        }
    }
}
